version: '3.7'

services:
  rmq-to-eventhub:
    #image: rabbitmq-to-eventhub-shovel:latest
    image: 029409915753.dkr.ecr.us-east-1.amazonaws.com/rabbitmq-to-eventhub-shovel:latest
    build:
      context: ../../../app
    user: 'node'
    restart: always
    working_dir: /home/node/app
    env_file:
      - ./conf/shovel.env
    volumes:
      - ./conf/:/home/node/app/conf/cert
    command: 'npm run start'

